package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/aashish47/finance-tracker/backend/internal/graphql/model"
	"github.com/aashish47/finance-tracker/backend/internal/platform/utils"
)

// Transactions is the resolver for the transactions field.
func (r *categoryResolver) Transactions(ctx context.Context, obj *model.Category, rangeArg *model.RangeInput) ([]*model.Transaction, error) {
	if obj.Transactions == nil {
		// fmt.Println("Category Transactions: ", time.Now().Format("15:04:05"))
		transactions, err := r.CategoryRepo.GetCategoryTransactions(obj.ID, rangeArg)
		if err != nil {
			return nil, err
		}
		obj.Transactions = transactions
	}
	return obj.Transactions, nil
}

// Total is the resolver for the total field.
func (r *categoryResolver) Total(ctx context.Context, obj *model.Category, rangeArg *model.RangeInput) (*float64, error) {
	if obj.Total == nil {
		// fmt.Println("Category Total: ", time.Now().Format("15:04:05"))
		total, err := r.CategoryRepo.GetCategoryTotal(obj.ID, rangeArg)
		if err != nil {
			return nil, err
		}
		obj.Total = total
	}
	return obj.Total, nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.TransactionInput) (*model.Transaction, error) {
	userId, err := utils.GetUserIDFromContext(ctx)

	if err != nil {
		return nil, err
	}

	newTransaction := &model.Transaction{
		Item:       input.Item,
		CategoryID: input.CategoryID,
		IsIncome:   input.IsIncome,
		Date:       input.Date,
		Amount:     input.Amount,
		UserId:     userId,
	}

	return r.TransactionRepo.CreateTransaction(newTransaction)
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id int, input model.UpdateTransactionInput) (*model.Transaction, error) {
	return r.TransactionRepo.UpdateTransaction(id, input)
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id int) (*model.Transaction, error) {
	return r.TransactionRepo.DeleteTransaction(id)
}

// Transactions is the resolver for the Transactions field.
func (r *queryResolver) Transactions(ctx context.Context, rangeArg *model.RangeInput) ([]*model.Transaction, error) {
	// fmt.Println("Transactions: ", time.Now().Format("15:04:05"))

	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetTransactions(userId, rangeArg)
}

// Transaction is the resolver for the Transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id int) (*model.Transaction, error) {
	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetTransaction(id, userId)
}

// GetCategoryTotals is the resolver for the getCategoryTotals field.
func (r *queryResolver) GetCategoryTotals(ctx context.Context, year int, month *int, search *string) ([]*model.CategoryTotal, error) {
	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetCategoryTotals(userId, year, month, search)
}

// GetMonthlyTotals is the resolver for the getMonthlyTotals field.
func (r *queryResolver) GetMonthlyTotals(ctx context.Context, year int, categoryID *int, search *string) ([]*model.MonthlyTotal, error) {
	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetMonthlyTotals(userId, year, categoryID, search)
}

// GetTransactionsPaginated is the resolver for the getTransactionsPaginated field.
func (r *queryResolver) GetTransactionsPaginated(ctx context.Context, year int, month *int, categoryID *int, page *int, limit *int, search *string, sort *string) (*model.TransactionConnection, error) {
	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetTransactionsPaginated(userId, year, month, categoryID, page, limit, search, sort)
}

// Categories is the resolver for the Categories field.
func (r *queryResolver) Categories(ctx context.Context, rangeArg *model.RangeInput) ([]*model.Category, error) {
	// fmt.Println("Categories: ", time.Now().Format("15:04:05"))

	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.CategoryRepo.GetCategories(userId, rangeArg)
}

// Category is the resolver for the Category field.
func (r *queryResolver) Category(ctx context.Context, id int, rangeArg *model.RangeInput) (*model.Category, error) {
	return r.CategoryRepo.GetCategory(id)
}

// Years is the resolver for the Years field.
func (r *queryResolver) Years(ctx context.Context) ([]*int, error) {
	// fmt.Println("Years: ", time.Now().Format("15:04:05"))

	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.CategoryRepo.GetYears(userId)
}

// LastDate is the resolver for the LastDate field.
func (r *queryResolver) LastDate(ctx context.Context) (*string, error) {
	// fmt.Println("LastDate: ", time.Now().Format("15:04:05"))

	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetLastTransactionDate(userId)
}

// Total is the resolver for the Total field.
func (r *queryResolver) Total(ctx context.Context, rangeArg *model.RangeInput) (*float64, error) {
	// fmt.Println("Total: ", time.Now().Format("15:04:05"))

	userId, err := utils.GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.TransactionRepo.GetTotal(userId, rangeArg)
}

// Category is the resolver for the category field.
func (r *transactionResolver) Category(ctx context.Context, obj *model.Transaction) (*model.Category, error) {
	if obj.Category == nil {
		// fmt.Println("Transactions Category: ", time.Now().Format("15:04:05"))
		category, err := r.TransactionRepo.GetCategoryForTransaction(obj.CategoryID)
		if err != nil {
			return nil, err
		}
		obj.Category = category
	}
	return obj.Category, nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type categoryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
