// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID           int            `json:"id"`
	Name         string         `json:"name"`
	Transactions []*Transaction `json:"transactions,omitempty"`
	Total        *float64       `json:"total,omitempty"`
}

type CategoryTotal struct {
	Category string  `json:"category"`
	Total    float64 `json:"total"`
	Count    int     `json:"count"`
}

type MonthlyTotal struct {
	Month int     `json:"month"`
	Total float64 `json:"total"`
	Count int     `json:"count"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RangeInput struct {
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type TransactionConnection struct {
	Edges      []*TransactionEdge `json:"edges"`
	PageInfo   *PageInfo          `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

type TransactionEdge struct {
	Node   *Transaction `json:"node"`
	Cursor string       `json:"cursor"`
}

type TransactionInput struct {
	Item       string  `json:"item"`
	CategoryID int     `json:"categoryID"`
	IsIncome   bool    `json:"isIncome"`
	Date       string  `json:"date"`
	Amount     float64 `json:"amount"`
}

type UpdateTransactionInput struct {
	Item       *string  `json:"item,omitempty"`
	CategoryID *int     `json:"categoryID,omitempty"`
	IsIncome   *bool    `json:"isIncome,omitempty"`
	Date       *string  `json:"date,omitempty"`
	Amount     *float64 `json:"amount,omitempty"`
}
